### ISSUE TITLE
Resource Requirements removed from manifests upgrading from 1.21 -> 1.22

### ISSUE THREAD

**Issue by caramcc** [cdk8s-team/cdk8s#1139]
### Description of the bug:

I'm in the process of upgrading a cluster from k8s@1.21 to k8s@1.22, configured using TypeScript CDK8s. Part of this upgrade involved needing to change all of the Container resource strings to `Quantity.fromString` because apparently that part of the schema changed. Now when I run `cdk diff` all of the resource requirements have been removed from the manifests.

E.g. I changed this part of container spec:
```typescript
resources: {
  limits: {
    cpu: '1.2',
    memory: '1G'
  },
  requests: {
    cpu: '400m',
    memory: '368M'
  }
```

to this:
```typescript
resources: {
  limits: {
    cpu: Quantity.fromString('1.2'),
    memory: Quantity.fromString('1G')
  },
  requests: {
    cpu: Quantity.fromString('400m'),
    memory: Quantity.fromString('368M')
  }
```

And now in my manifests, I am seeing:
```
"resources":{"limits":{},"requests":{}}
```

instead of the expected:
```
"resources":{"limits":{"cpu":"1.2","memory":"1G"},"requests":{"cpu":"400m","memory":"368M"}}
```

### Reproduction Steps:

Not sure of the minimal reproduction steps here, I'm not very familiar with CDK8s as I inherited this k8s cluster and its config. I assume that creating a container spec with those resource requests will also fail to configure resources properly.

Let me know if there is any information I can provide that would help to reproduce or triage this!

### Environment:

  - **Framework Version**: Typescript CDK8s version 1.5.58
  - **OS**: Linux

---

This is :bug: Bug Report

**Comment by caramcc** [comment]
Apologies, this appears to have been a bug on our side.

**Comment by iliapolo** [comment]
@caramcc you mind sharing what exactly was the bug on your side? Might be beneficial for posterity and the community :)
