### ISSUE TITLE
Python Set up instructions points to a site with broken SSL

### ISSUE THREAD

**Issue by ckdarby** [cdk8s-team/cdk8s#1145]
### Description of the bug:
When following the set up instructions https://pipenv.kennethreitz.org has an SSL cert error.

> "Initializing a project from the python-app template
Unable to find "pipenv". Install from https://pipenv.kennethreitz.org"

```text
$ mkdir hello
$ cd hello
$ cdk8s init python-app
Initializing a project from the python-app template
```

### Environment:
  - **OS**: Ubuntu 22.04

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@ckdarby Thanks for this. We will take a look.
