### ISSUE TITLE
Golang Support

### ISSUE THREAD

**Issue by eladb** [cdk8s-team/cdk8s#119]
Tracking issue for Golang support in cdk8s. Please +1 this issue to let us know you care (no need to comment).

Remaining work:

- [x] https://github.com/cdk8s-team/cdk8s-cli/issues/26
- [x] https://github.com/cdk8s-team/cdk8s-cli/issues/27
- [x] https://github.com/cdk8s-team/cdk8s/issues/637

**Comment by saran-007** [comment]
@eladb - My team and I are interested in exploring contributions to Golang support. Is there any effort started that we can join on? any directions will help.

**Comment by vladimir-setka-form3** [comment]
All three linked issues have been resolved. Does this mean Go support is on the horizon? I don't see much activity here https://github.com/cdk8s-team/cdk8s-go

**Comment by Hunter-Thompson** [comment]
> All three linked issues have been resolved. Does this mean Go support is on the horizon? I don't see much activity here https://github.com/cdk8s-team/cdk8s-go

https://github.com/cdk8s-team/cdk8s/tree/master/examples/go/hello

: )

Also, the repo to look out for is this one : https://github.com/cdk8s-team/cdk8s-core-go
