### ISSUE TITLE
The synth produces empty templates when modules with constructs not imported from a package

### ISSUE THREAD

**Issue by OperationalFallacy** [cdk8s-team/cdk8s#1214]
### Description of the bug:

We've developed a lib with constructs, publishing it on the internal npm registry. We want to import modules directly to make development faster, bypassing npm packaging. Npm has a feature for this https://docs.npmjs.com/cli/v9/commands/npm-link

When it is used, cdk synth creates empty templates 

### Reproduction Steps:

`import { myconstruct } from "../mylib"` (or using package name after applying `npm link`)

### Error Log:

No errors, constructs that imported from the package sythed correctly, alongside empty files for constructs imported from the filesystem

### Environment:

OSx, Node18

### Other:

I can capture stack trace or debug info, but I am not sure what to do it with the cli. It should be pretty easy to reproduce as well.

---

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@OperationalFallacy Can you share your exact setup please? That is, which dependencies are defined in the library that is being linked, and which ones are defined in the library that does the linking?

**Comment by shinebayar-g** [comment]
I have a similar setup. I don't use `npm link`, but this gets the job done. NPM package is cloned & extracted from the git repository.
```json
  "dependencies": {
    "my-cdk8s-library": "git+ssh://git@github.com:my-org/my-cdk8s-library.git#semver:v0.5.0"
  },
```
