### ISSUE TITLE
RFC | Helm Import

### ISSUE THREAD

**Issue by vinayak-kukreja** [cdk8s-team/cdk8s#1271]
## Description

Currently cdk8s supports adding helm charts as construct with the [helm construct](https://cdk8s.io/docs/latest/basics/helm/). This approach does not take into consideration data types for the values that the helm chart can accept.

This RFC is proposing to enable users to import a helm chart as a construct using `cdk8s import`. This would auto generate a construct for the user and if a `values.schema.json` is present in the helm chart, then the `values` properties would have appropriate types associated with them.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @vinayak-kukreja 
| Author(s)           | @vinayak-kukreja 
| API Bar Raiser      | @iliapolo 
| Stakeholders        | @cdk8s-team/cdk8s-team 

> See [RFC Process](https://github.com/cdk8s-team/cdk8s#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `rfc/proposed`)
- [x] API bar raiser assigned (ping us at [#cdk8s](https://cdk-dev.slack.com/archives/C0184GCBY4X) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `rfc/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `rfc/api-approved` applied to pull request)
- [x] Final comments period (label: `rfc/final-comments-period`)
- [x] Approved and merged (label: `rfc/approved`)
- [x] Execution plan submitted (label: `rfc/planning`)
- [x] Plan approved and merged (label: `rfc/implementing`)
- [ ] Implementation complete (label: `rfc/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by yuriy-yarosh** [comment]
I've made a basic helm charts import with codegen over imported k8s structs, using prerendered `helm template` charts, for golang. The issue I've faced is that it required a stacked codegen to reduce the boilerplate for golang specifically. I could contribute the respective JSII bindings as well, but the user still would need to provide a `values.yaml` for the `helm template` somewhere.

**Comment by iliapolo** [comment]
@yuriy-yarosh the values will still be provided as normal. But instead of providing it to a generic `Helm` construct, they will provide it to a specific `Airflow` construct (for example), where the values dictionary will now be typed. 

Im not sure I understand what you mean by stacked codegen, do you have an example to show?
