### ISSUE TITLE
ts-node: command not found

### ISSUE THREAD

**Issue by andiMenge** [cdk8s-team/cdk8s#1273]
### Description of the bug:

`cdk8s synth` fails with the error message below. It looks like `ts-node` needs to be globally installed, b/c a `npm install -g ts-node` resolves the issue. Based on the getting started guide, I did assume that no additional install steps are necessary. When I noticed that `ts-node` was included in the project scaffolding as a devDependency it did surprise me that the CLI is not using the ts-node version bundled with the project.

- `cdk8s` version: 2.2.10

### Reproduction Steps:

1. `npm install -g cdk8s-cli`
2. `cdk8s init typescript-app`
3. `npm run compile && cdk8s synth`

### Error Log:

```
Synthesizing application
/bin/sh: ts-node: command not found
Error: command "ts-node main.ts " at <redact> returned a non-zero exit code 127
    at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/cdk8s-cli/lib/util.js:51:27)
    at Object.onceWrapper (node:events:627:26)
    at ChildProcess.emit (node:events:512:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

### Environment:

  - **Framework Version**: "typescript": "4.9.5"
  - **OS**: macOS 13.3 (M1)

### Other:

---

This is :bug: Bug Report

**Comment by shinebayar-g** [comment]
Yep, just run into this issue. Looks like typescript template is [trying to invoke ts-node directly](https://github.com/cdk8s-team/cdk8s-cli/blob/2.x/templates/typescript-app/cdk8s.yaml#L2) assuming it's available in the `PATH`.

```json
{
  "name": "cdk8s-test",
  "version": "1.0.0",
  "main": "main.js",
  "types": "main.ts",
  "license": "Apache-2.0",
  "private": true,
  "scripts": {
    "import": "cdk8s import",
    "synth": "cdk8s synth",
    "compile": "tsc --build",
    "watch": "tsc --build -w",
    "test": "jest",
    "build": "npm run compile && npm run test && npm run synth",
    "upgrade": "npm i cdk8s@latest cdk8s-cli@latest",
    "upgrade:next": "npm i cdk8s@next cdk8s-cli@next"
  },
  "dependencies": {
    "cdk8s": "^2.7.54",
    "cdk8s-plus-25": "^2.6.18",
    "constructs": "^10.1.302"
  },
  "devDependencies": {
    "@types/jest": "^26.0.24",
    "@types/node": "^14.18.42",
    "cdk8s-cli": "^2.2.10",
    "jest": "^26.6.3",
    "ts-jest": "^26.5.6",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5"
  }
}
```

This was the `package.json` that was generated during the initialization. Since `ts-node` is part of the devDependencies and then there is `"synth": "cdk8s synth",` script defined, you should be able to run `npm run synth` to invoke cdk8s synth.

**Comment by iliapolo** [comment]
Ouch, sorry about this folks. @andiMenge thanks for reporting and thanks @shinebayar-g for working on a fix. In the meantime you can also change `cdk8s.yaml` to use `npx ts-node main.ts`.

**Comment by andiMenge** [comment]
Awesome. Thank you 😊
