### ISSUE TITLE
Is there way to convert yaml to cdk8s typescript file (.ts)

### ISSUE THREAD

**Issue by chethankumar4046** [cdk8s-team/cdk8s#1275]
I have simple deployment yaml, 
I want to convert that yaml file to .ts (cdk8s) cdk8s-plus-23

imput.yaml
[deployment.yaml.zip](https://github.com/cdk8s-team/cdk8s/files/11188376/deployment.yaml.zip)
output.ts
[deployment.ts.zip](https://github.com/cdk8s-team/cdk8s/files/11188379/deployment.ts.zip)

**Comment by iliapolo** [comment]
There is no way to convert a yaml manifest to cdk8s-plus `Deployment` construct. But you can convert it to a `KubeDeployment` class. Have a look at [kube2cdk8s](https://github.com/smallcase/kube2cdk8s) project.
