### ISSUE TITLE
CDK8s: How to not prefix my image URI with docker://

### ISSUE THREAD

**Issue by deniscitaku** [cdk8s-team/cdk8s#1282]
I have a Deployment stack where I specify an image from AWS ECR but after compiling and synthesizing this image, URI is added a `docker://` prefix which is causing the deployment to fail initializing because the image source is changed from this: `${accountId}.dkr.ecr.${region}.amazonaws.com/${appName}:${tagName}` to this: `docker://${accountId}.dkr.ecr.${region}.amazonaws.com/${appName}:${tagName}`. Here's my deployment:
```
new Deployment(this, `${appName}-deployment`, {
      metadata: {
        name: appName,
        labels: { appName, appVersion },
      },
      select: true,
      containers: [ {
        image: `${accountId}.dkr.ecr.${region}.amazonaws.com/${appName}:${tagName}`,
        ports: [
          { protocol: Protocol.TCP, name: 'http', number: port },
        ],
        securityContext: { ensureNonRoot: false }
      } ],
      replicas: 1,
      dockerRegistryAuth: Secret.fromSecretName(this, `${appName}-ecr-registry-secret`, 'ecr-registry-secret')
    })
```
after compiling, looking at the `dist/cdk8s.k8s.yml` the image is translated to this:
```
image: docker://11111111.dkr.ecr.region-1.amazonaws.com/app-name:1.0
```
When I manually remove the docker prefix, my deployment works as expected but I can't find I way to do that without manual intervention. My question is, how can I specify the image URI without the `docker://` prefix?

**Comment by iliapolo** [comment]
@deniscitaku Nothing in cdk8s is adding such a prefix...are you absolutely sure its coming from cdk8s? is it possible your `${accountId}` is somehow populated with that before invoking cdk8s?
