### ISSUE TITLE
Support for Aspects on chart synthesis

### ISSUE THREAD

**Issue by msessa** [cdk8s-team/cdk8s#1312]
### Description of the feature or enhancement:

Introduce support for visiting [Aspects](https://docs.aws.amazon.com/cdk/v2/guide/aspects.html) attached to cdk8s constructs upon chart synthesis.

### Use Case:

Aspects are a useful feature to extend constructs at synth time, eg (adding HPAs/PDBs to all Deployment/StatefulSets if a user didn't explicitly declare any)

### Proposed Solution:

Introduce recursive aspect visiting logic [similar to CDK](https://github.com/aws/aws-cdk/blob/a0ad49df7b2536d800b4890ae0116e6ce26e6c55/packages/aws-cdk-lib/core/lib/private/synthesis.ts#LL217C7-L217C7)

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@msessa Yeah we've been thinking about Aspects for a while. I think we should consider adding it the the `constructs` library with support for custom type hooking (if possible).

We're not going to be able to get to this any time soon, so I'm marking this as a p2. But if we see increased community interest we might reprioritize.
