### ISSUE TITLE
Install multiple CRDs via single remote URL

### ISSUE THREAD

**Issue by jackpordi** [cdk8s-team/cdk8s#1332]
### Description of the feature or enhancement:

Many Helm Charts are now publishing their CRDs as multiple, separate manifests, e.g. Traefik.
I'd like to be able to do the following command via `cdk8s`:

`kubectl apply --server-side --force-conflicts -k https://github.com/traefik/traefik-helm-chart/traefik/crds/`

I have tried to do 

```
    new Include(this, 'dashboard', {
      url: 'https://github.com/traefik/traefik-helm-chart/traefik/crds/',
    });

```
But this does not work as I get a 404.

### Use Case:

To install CRDs that are published as multiple files separately from Helm charts.

### Proposed Solution:

Allow `Include` to work with remote directories as well.

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jackpordi** [comment]
Just realized this is

**Comment by iliapolo** [comment]
@jackpordi I'm interested in this - why do you say its essentially Kustomize support? I see it more as a request for the `Include` construct to be able to handle github directory URLs? Specifically in the example you posted, the `kustomization.yaml` file doesn't really do anything except for list of the files in that directory.
