### ISSUE TITLE
Add validation for values

### ISSUE THREAD

**Issue by yairyairyair** [cdk8s-team/cdk8s#1338]
I want that cdk8s will verify some values that kubernetes api server already validates, 
for example if you input a i valid deployment name and apply in kubernetes it will give you an error that a deployment name needs to be of regex....
We need that same regex validation after the cdk8s generate or somewhere.

Let me know your thoughts

**Comment by mcouthon** [comment]
Encountered this now as well. Someone added an underscore to a string that went in a label. The synth passed fine, and we only discovered it at deploy time. 
Do you have a good workaround for that, maybe? Is there some ability to pass a validator to the synth command? Us implementing this from scratch wouldn't be prudent.
