### ISSUE TITLE
Support for k8s `1.27`

### ISSUE THREAD

**Issue by dverheijden** [cdk8s-team/cdk8s#1339]
### Description of the feature or enhancement:

I've noticed that there aren't any CRDs yet for k8s `1.27`, nor was there an issue yet. Is there a timeline for releasing the CRDs?

[Amazon EKS now supports Kubernetes version 1.27](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-27/)

### Use Case:

For updating applications running on EKS `1.27`.

### Proposed Solution:

Add `v1.27.0` kubernetes schema.

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Thanks @dverheijden - we will be working on this shortly 👍

**Comment by dverheijden** [comment]
Thanks for resolving this issue. It was https://github.com/cdk8s-team/cdk8s/pull/1360 for bookkeeping.
