### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by eladb** [cdk8s-team/cdk8s#134]
This is an aggregate issue for language support. Please +1 on specific languages or open a new issue if a language you are looking for doesn't have an issue and link it from this issue via a comment.

Language support will be added through [jsii](https://github.com/aws/jsii). If you are interested to help, please reach out.

**Comment by eladb** [comment]
.NET: #118

**Comment by eladb** [comment]
Java: #117

**Comment by eladb** [comment]
Golang: #119

**Comment by jk-gan** [comment]
Rust: #152

**Comment by rask** [comment]
PHP: #157

**Comment by zacblazic** [comment]
Ruby: https://github.com/awslabs/cdk8s/issues/158

**Comment by inge4pres** [comment]
Maybe dumb question: is there an overview of what it takes to create a new language support? Sort of a technical description of the requirements and how to get started with it

**Comment by eladb** [comment]
> Maybe dumb question: is there an overview of what it takes to create a new language support? Sort of a technical description of the requirements and how to get started with it

Language support will be added through [jsii](https://github.com/aws/jsii) which should have details on what it takes to add a new language. It’s a rather major endeavor which we are tackling one by one. Next up is Go.

**Comment by iliapolo** [comment]
Closing in favor of the language specific issues we have.

- .NET: https://github.com/cdk8s-team/cdk8s/issues/118
- Rust: https://github.com/cdk8s-team/cdk8s/issues/152
- Golang: https://github.com/cdk8s-team/cdk8s/issues/119
- PHP: https://github.com/cdk8s-team/cdk8s/issues/157
- Ruby: https://github.com/cdk8s-team/cdk8s/issues/158
- Java: Already supported
