### ISSUE TITLE
cdk8s dasm: convert a yaml manifest to a cdk8s chart

### ISSUE THREAD

**Issue by eladb** [cdk8s-team/cdk8s#141]
We propose a new command called `cdk8s dasm` that will take a k8s yaml as input and will generate code (in one of the supported programming languages) which will synthesize the same manifest output (as much as possible).

It's nice way to migrate from manifests to cdk8s.

See the [cdk-dasm](https://www.npmjs.com/package/cdk-dasm) as an example.

**Comment by carltonmason** [comment]
This would be awesome feature!

**Comment by pgollucci** [comment]
Yes definitely this one. 👍

**Comment by moises-perez-tfs** [comment]
I was exploring to find a feature like this. Our use case is to automate the management (add, remove) of Identity Mappings in the aws-auth in EKS. Is this feature also going to be available in code (not just command) to enable automation?

**Comment by iliapolo** [comment]
@moises-perez-tfs We still don't have a concrete plan for this feature. Noted that it would be good to have it available via an API as well :)

**Comment by Chriscbr** [comment]
Keep

**Comment by Hunter-Thompson** [comment]
I wrote a little something to help make this a bit easier.  The following project can convert your YAML to an APIObject.

It uses kube2pulumi as a base.

https://github.com/smallcase/kube2cdk8s

**Comment by eladb** [comment]
@Hunter-Thompson very cool! Curious - why did you need to use `kube2pulumi` as a base?

**Comment by Hunter-Thompson** [comment]
> @Hunter-Thompson very cool! Curious - why did you need to use `kube2pulumi` as a base?

I first convert it to a Pulumi object, then remove the Pulumi specific things with cdk8s specific declarations. Its a hack, but since both the API's are the same, it works :)

1st result : 
```
import * as pulumi from "@pulumi/pulumi";
import * as kubernetes from "@pulumi/kubernetes";

const frontendNginxPod = new kubernetes.core.v1.Pod("frontendNginxPod", {
    apiVersion: "v1",
    kind: "Pod",
    metadata: {
        namespace: "frontend",
        name: "nginx",
    },
    spec: {
        containers: [{
            name: "nginx",
            image: "nginx:1.14-alpine",
            resources: {
                limits: {
                    memory: "20Mi",
                    cpu: 0.2,
                },
            },
        }],
    },
});
```

After parsing : 

```
new k8s.KubePod(this, "nginx", {
    metadata: {
        namespace: "frontend",
        name: "nginx",
    },
    spec: {
        containers: [{
            name: "nginx",
            image: "nginx:1.14-alpine",
            resources: {
                limits: {
                    memory: "20Mi",
                    cpu: 0.2,
                },
            },
        }],
    },
});
```

**Comment by gkarthiks** [comment]
I am working on some use cases that need to append resources regularly. I am using cdk8s on go language. Looking for this kind of feature on the code. Say, read an existing YAML manifest and append that with additional data and put it back. So that the GitOps Engine will look at the change and applies that on to the cluster.

Definitely a needed feature...

**Comment by hemzaz** [comment]
Waiting for this feature :)

**Comment by jmreicha** [comment]
Take it this is never going to happen now with the creator working on a different project?

**Comment by iliapolo** [comment]
@jmreicha 

We don't currently have this on our immediate roadmap. There is third-party project that might help you out though: https://github.com/smallcase/kube2cdk8s

**Comment by iliapolo** [comment]
For those interested in this in order to augment existing YAML manifests with resources defined in code, have a look at the [Include](https://cdk8s.io/docs/latest/basics/include/) construct, which can help with that.
