### ISSUE TITLE
Add support for Exbibyte

### ISSUE THREAD

**Issue by vinayak-kukreja** [cdk8s-team/cdk8s#1426]
### Description of the feature or enhancement:

Currently, `Exbibyte` does not exists as a storage unit. It probably requires `BigInt` since it is higher than `MAX_SAFE_INTEGER`. 

### Use Case:
It is a unit that is available to be used in Kubernetes.

### Proposed Solution:
Implement `Exbibyte` in `Size`: https://github.com/cdk8s-team/cdk8s-core/blob/2.x/src/size.ts#L129-L130

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by amanpandey3956** [comment]
Do assign me this issue would love to work on it
