### ISSUE TITLE
Example and Integration with ArgoCD

### ISSUE THREAD

**Issue by Rep1AI** [cdk8s-team/cdk8s#162]
Can Real-world examples with CI/CD pipeline like Argo be included?

**Comment by ryanvade** [comment]
I've been looking at using Argo Workflows and Argo Events with cdk8s.  It seems their CRD manifests don't fully define the field attributes so the import tool doesn't pull them in.  Unless I'm missing something an example with Argo Workflows, Argo Events, or Argo CD will require manual type definitions for the CRDs.

**Comment by zeemy23** [comment]
That can be pretty easily achieved in a day or 2 using argocd's config management plugin: https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/

This tool is very exciting!

**Comment by RohitR1** [comment]
Is it possible to add a full end to end example with that?

**Comment by iliapolo** [comment]
I'd like to explore this further, re-opening.

**Comment by aakankshabhende** [comment]
I would like to work on this issue @iliapolo @Chriscbr

**Comment by iliapolo** [comment]
@aakankshabhende that would be great. Do you have a direction in mind?
