### ISSUE TITLE
Explain the need for using cdk8s-cli vs executing the cdk8s script file directly?

### ISSUE THREAD

**Issue by shinebayar-g** [cdk8s-team/cdk8s#1806]
### Description of the feature or enhancement:

Is there any difference between using [cdk8s-cli](https://github.com/cdk8s-team/cdk8s-cli) vs just calling the `.synth()` method?
```sh
yarn run cdk8s synth --app 'yarn run tsx main.ts'
```
vs
```sh
yarn run tsx main.ts
```
Both method worked for me. Except the latter doesn't show outputs obviously. Am I missing anything by not using the cli?

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
For the purpose of solely creating a YAML manifest, no there is no difference. But there are some auxiliary features that are only implemented in the CLI (though arguably could be moved to the framework) like:

- https://cdk8s.io/docs/latest/cli/synth/#validating-manifests 
- https://cdk8s.io/docs/latest/cli/synth/#helm-synthesis
