### ISSUE TITLE
Ability to disable Version warning

### ISSUE THREAD

**Issue by markussiebert** [cdk8s-team/cdk8s#1964]
### Description of the feature or enhancement:
I would like to get rid of output like:

```bash
------------------------------------------------------------------------------------------------
A new version 2.198.127 of cdk8s-cli is available (current 2.198.93).
Run "npm install -g cdk8s-cli" to install the latest version on your system.
For additional installation methods, see https://cdk8s.io/docs/latest/getting-started
------------------------------------------------------------------------------------------------
```

There should be a flag that allows me to disable it

### Use Case:
I want to parse the output, and don't want to have this on my stdout

### Proposed Solution:
add a flag to cdk8s synth

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by burner1024** [comment]
Should be a config option, really.

Furthermore, the link it gives in the banner is 404.
