### ISSUE TITLE
Roadmap link in the readme is broken

### ISSUE THREAD

**Issue by renannprado** [cdk8s-team/cdk8s#2132]
<img width="636" alt="image" src="https://github.com/user-attachments/assets/fba0af0c-fab4-49f8-8530-77ad764d8216">

**Comment by parthlaw** [comment]
What should be the actual link? The url points to projects but there is no project in the Projects section.

**Comment by applike-ss** [comment]
@mrgrain Is it possible the project is setup to private instead of publich in terms of access permissions?

**Comment by mrgrain** [comment]
> @mrgrain Is it possible the project is setup to private instead of publich in terms of access permissions?

No, I don't see any projects either.

**Comment by renannprado** [comment]
@mrgrain @parthlaw @applike-ss if this is resolved, maybe it also helps to clean this doubt here:

https://github.com/cdk8s-team/cdk8s/discussions/2052 Is this project still being maintained?

**Comment by applike-ss** [comment]
To me it is not resolved and the project status is unknown
