### ISSUE TITLE
Design decision documentation for constructs

### ISSUE THREAD

**Issue by FlorianLudwig** [cdk8s-team/cdk8s#231]
### Description of the feature or enhancement:

I've been playing around with cdk8s and have not fully understood what `Constructs` are for / how they are meant to be used.  As I write a lot more python than typescript - this is from my personal python-focused view :)

I marked this a feature request as I am looking for more documentation. (But could just be as well just a question ;))

From the docs:
> They are the instrument that enables composition and creation of higher-level abstractions through normal object-oriented classes.

But what are they actually doing?  From the examples they just look like a list/array.

The example:

```python
class MyChart(Chart):
    def __init__(self, scope: Construct, name: str):
        super().__init__(scope, name)

        k8s.Service(self, 'service', ...)
        k8s.Deployment(self, 'deployment', ...)

app = App()
MyChart(app, "hello")

app.synth()
```

could just as well be:

```python

chart = [
  k8s.Service('service', ...)
  k8s.Deployment('deployment', ...)
]

k8s.synth(chart)
```

What does `k8s.Service` use the chart for? It looks like you can use it to specify a different default namespace. (I think, found that by looking through the code, would be great if documented) What else?

I also found: https://github.com/aws/constructs - it refers to itself as "Constructs Programming Model" and I wasn't able to find documentation explaining the model / concept nor API documentation.

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
I agree we need more conceptual documentation in this project.

The main purpose of constructs is to enable composition. The idea is that a construct represents an abstract component that can be implemented by means of other constructs.

You can find some more conceptual documentation in the [AWS CDK Developer Guide](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html).

Let me know if these docs help.
