### ISSUE TITLE
Documentation about name generation

### ISSUE THREAD

**Issue by FlorianLudwig** [cdk8s-team/cdk8s#232]
### Description of the feature or enhancement:

Names (as in `.metadata.name`) are automatically generated from the name given to the construct. This is a request to add to the documentation: How are those names generated, especially how stable are they? (As in when do they change)

As #217 points out is it possible to workaround this but I like to add the reasoning why this is done to the documentation and what use cases this supports. And maybe even add the workaround for use cases where this might be harmful.

---

This is a :rocket: Feature Request

**Comment by itajaja** [comment]
for everyone stumbling on this issue, I had the same question so after some code digging I found out that this is the identifier that gets hashed: [`Node.Path`](https://github.com/aws/constructs/blob/master/src/construct.ts#L87) in the constructs library. So, the hashes are stable as long as the names that enclose the node remains unchanged. I think it's also useful to add to the documentation a suggestion on how to drop the hashes. I overrode the `generateObjectName` function like so:

```ts
generateObjectName(apiObject: ApiObject) {
    return Names.toDnsLabel(apiObject, { includeHash: false });
  }
```

to prevent including hashes.

**Comment by rrey-aviatrix** [comment]
@Chriscbr I did not find the answer to that same initial question in the doc.
It would be better to kill the question early in the doc around the name management and how it is generated.

Since the resource name is important in k8s, the information is important as well.

**Comment by jhwbarlow** [comment]
Thanks @itajaja for the hint, this works for me with Python:

```python
from constructs import Construct
from cdk8s import App, Chart, Names, ApiObject

class ExampleChart(Chart):
    def generate_object_name(self, api_object: ApiObject) -> str:
        return Names.to_dns_label(api_object, include_hash=False)

    def __init__(self, scope: Construct, id: str):
        super().__init__(scope, id)

    ....

```

**Comment by sapslaj** [comment]
We ran into this with the Go. It's a little trickier since Go doesn't natively support overrides but jsii provides a way to work around that. You just have to make your own `struct`, add the `GenerateObjectName` method to it, then make a constructor function that sets up the overrides with the jsii kernel. Here's the code:

```go
package chart
​
import (
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/jsii-runtime-go"
	"github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2"
)
​
type chartProxy struct {
	cdk8s.Chart
}
​
func NewChart(scope constructs.Construct, id *string, props *cdk8s.ChartProps) cdk8s.Chart {
	c := &chartProxy{}
	cdk8s.NewChart_Override(c, scope, id, props)
	return c
}
​
func (c *chartProxy) GenerateObjectName(apiObject cdk8s.ApiObject) *string {
	return cdk8s.Names_ToDnsLabel(apiObject, &cdk8s.NameOptions{
		IncludeHash: jsii.Bool(false),
	})
}
```

And then instead of calling `cdk8s.NewChart(...)` just call `chart.NewChart(...)` with the same args. And presto, no hashes in the names.

**Comment by iliapolo** [comment]
@sumupitchayan To resolve this issue we want to add a section to our website. I think an appropriate place would be to add a "Resource Names" section [here](https://cdk8s.io/docs/latest/basics/api-object/) that explains the name generation process:

- When are they generated
- How are they generated
- Why are hashes used. (see https://docs.aws.amazon.com/cdk/v2/guide/identifiers.html)
