### ISSUE TITLE
Docker assets

### ISSUE THREAD

**Issue by tabern** [cdk8s-team/cdk8s#26]
Similarly to AWS CDK, cdk8s should provide a way to bundle docker images in constructs to support end-to-end "gitops" experience.

Imagine your cdk8s app includes both the k8s definitions and your application code (rooted by a Dockerfile).

Then you, commit a change to any of these and your cluster is updated.

**Comment by ajaegle** [comment]
I'm not sure if those two steps should be done in the same step/tool. Why do I think so? In my opinion, building artifacts (docker images) should be independent from the deployment process. Having that tightly integrated into the various stacks also means to have the image rebuilt for every stage which destroys the big advantage of being sure that the same artifact that was tested on a test stage is also used in production.

When those two steps (building and deploying) are integrated heavily, you would rebuild your docker image just before deploying to prod, maybe producing an image that is not exactly the one you had before (e.g. the base image got a bugfix, some transitive npm dependency was updated or any other issue of the build machine affecting the build).

This is why I prefer the way of building images once and promoting them from one stage to the other by either retagging, pushing to another registry, updating the shasum used in the image reference.

I like cdk8s to be the tool that does one thing and does that right - which is synthesizing manifests specified in code.

**Comment by eladb** [comment]
See https://github.com/cdk8s-team/cdk8s-image
