### ISSUE TITLE
Add documentation on how to vend cdk8s based libraries

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s#263]
Lets add some guidance on how to vend libraries like `cdk8s-plus`. Essentially ones that rely on the auto-generated code produced by the cdk8s-cli. This flow is a little different from normal library authoring.

**Comment by edobry** [comment]
Hello, would love to see some more guidance around this; currently working on an internal chart construct library and running into toolchain issues. Thanks

**Comment by iliapolo** [comment]
Keep
