### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s#422]
We should officially support windows before announcing GA. This means adding some windows CI in GitHub actions as well.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by campionfellin** [comment]
Some notes on this:

* Github actions does not support container actions for Windows ([docs here](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#types-of-actions)) and [failed build here](https://github.com/campionfellin/cdk8s/runs/1478264468?check_suite_focus=true)
* We've been piggy-backing off the [`jsii/superchain`](https://github.com/aws/jsii/tree/main/superchain) image which is built on AL2 and includes a bunch of language SDKs and tools.

I thiiink what would need to be done for this to work is a bunch of steps in the [`build.yml`](https://github.com/awslabs/cdk8s/blob/master/.github/workflows/build.yml#L10) workflow that installs everything that's needed.

The JSII/superchain [Dockerfile](https://github.com/aws/jsii/blob/main/superchain/Dockerfile) is probably a good place to get started.

---

Thoughts on just more-or-less replicating that Dockerfile in the Github workflow steps?

**Comment by iliapolo** [comment]
@campionfellin I don't think we actually need to *build* on windows, we just need to run the integration tests, which should only require `node/python/java`.

This means we won't officially support windows as a development machine, but thats ok, we are targeting runtime.

**Comment by campionfellin** [comment]
@iliapolo great point! I think I can take this one if no one else has started on it

**Comment by iliapolo** [comment]
@campionfellin that would be awesome, thanks! :)

**Comment by campionfellin** [comment]
@iliapolo somewhat stuck here, do you have any windows experience? I'm getting the error:

`cdk8s: command not found`

On the first integration test here:

https://github.com/awslabs/cdk8s/blob/ac295fe78544c4b06f732fe945dfa6423eea5c83/test/test-imports/python/test.sh#L14

This is what I've tried so far:

1. Verified it's in the path and executable by `ls -al` the path:

https://github.com/awslabs/cdk8s/blob/ac295fe78544c4b06f732fe945dfa6423eea5c83/test/run-against-dist#L18-L24

```
-rwxr-xr-x 1 runneradmin 197121 324 Dec  4 03:29 cdk8s
-rw-r--r-- 1 runneradmin 197121 279 Dec  4 03:29 cdk8s.cmd
-rwxr-xr-x 1 runneradmin 197121 494 Dec  4 03:29 cdk8s.ps1
```

2. Also tried running the `cdk8s.cmd` instead.
3. Set the shell to `bash`
4. Set all the script headers to `#!/bin/bash` instead of `#!/bin/sh`

**Comment by iliapolo** [comment]
@campionfellin 

> Set the shell to bash

What do you mean by that? How are you running these scripts? can you share a link to the workflow? 

I think we need a windows version of all the scripts running the integration tests, or better yet, convert them to nodejs scripts.

**Comment by iliapolo** [comment]
@campionfellin Can't say I know what's happening...do you have capacity to keep hacking on it? lets sync up online.

**Comment by campionfellin** [comment]
@iliapolo finally got testing to work this morning! The tests fail on Windows, but at least they run now. My plan here is to:

1. Clean that code up a bit and open a PR that adds the Windows step to the pipeline.
2. Work separately on PRs that fix failing tests on Windows.
3. Continually merge from mainline into the first PR until it passes, then merge it itself.
