### ISSUE TITLE
Collect available KPI's we can use to evaluate engagement 

### ISSUE THREAD

**Issue by eladb** [cdk8s-team/cdk8s#487]
We need to find a way to collect usage analytics through the CLI or the library.

**Comment by balibebas** [comment]
-1 on telemetry

**Comment by iliapolo** [comment]
Proposed metrics/data to periodically inspect:

- `cdk8s-cli` download [stats](https://npm-stat.com/charts.html?package=cdk8s-cli) from NPM.
- Per language download stats for framework libraries:

  - **NPM**: [cdk8s](https://npm-stat.com/charts.html?package=cdk8s) | [cdk8s-plus-17](https://npm-stat.com/charts.html?package=cdk8s-plus-17)
  - **PyPI**: [cdk8s](https://pypistats.org/packages/cdk8s) | [cdk8s-plus-17](https://pypistats.org/packages/cdk8s-plus-17)
  - **Maven**: TBD
  - **Golang**: TBD

- Page hits to `cdk8s.io`
- CNCF provided devstats:

- TBD

**Comment by Chriscbr** [comment]
If we publish to homebrew, we can also get download counts from there.

**Comment by iliapolo** [comment]
We still want to figure this out. Giving it another try.

**Comment by Chriscbr** [comment]
An additional source of metrics that might be worth looking into are the GitHub org/repository metrics: https://docs.github.com/en/rest/reference/repository-metrics#traffic
