### ISSUE TITLE
DCO check is missing for the cdk8s project

### ISSUE THREAD

**Issue by idvoretskyi** [cdk8s-team/cdk8s#508]
Greetings, project maintainers.

CNCF's IP policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy) requires all projects to use either CLA (Contributor License Agreements) or DCO (Developer Certificate of Origin). Unless there's a strong necessity to use CLA, we encourage projects to use DCO as it's easier to setup and use. Ref.: https://github.com/cncf/foundation/issues/130

During the audit, we've noticed that one or a few repositories of your project doesn't have the DCO check enabled. Please enable the DCO check for all repositories owned by your project. You may find more details here - https://github.com/apps/dco.

Thanks

**Comment by eladb** [comment]
Thanks @idvoretskyi we will take care of this as soon as possible.

**Comment by eladb** [comment]
Keep

**Comment by eladb** [comment]
Keep

**Comment by iliapolo** [comment]
Closing as all repositories have added DCO checks. (See above PR links)
