### ISSUE TITLE
Integration: DeepSource

### ISSUE THREAD

**Issue by withshubh** [cdk8s-team/cdk8s#538]
### Description
I ran DeepSource analysis on my fork of this repository and found some code quality issues. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/cdk8s/issues/?category=recommended).

[DeepSource](https://deepsource.io/) is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code. 

PR #504 fixed some of the issues caught by DeepSource.

All the features of the DeepSource are mentioned [here](https://deepsource.io/features/).
I'd suggest you integrate DeepSource since it is free for Open Source projects forever.

#### Activating DeepSource to continuously analyze your repository:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Create `.deepsource.toml` configuration specific to this repo or use the configuration mentioned below which I used to run the analysis on the fork of this repo.
- Activate analysis [here](https://deepsource.io/gh/awslabs/cdk8s/).

```
version = 1

test_patterns = ["/test/**/*.ts"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  dialect = "typescript"

```

### Other:

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
Thanks for the suggestion. We will consider this if/when we decide to integrate a code quality tool.
