### ISSUE TITLE
Golang What's New / Blog Post

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s#564]
We need to publish an official announcement in some way.

**Comment by prateeknayak** [comment]
Hey Folks, just wondering if there is a timeline for when the golang support would be available?

**Comment by Hunter-Thompson** [comment]
> Hey Folks, just wondering if there is a timeline for when the golang support would be available?

Go support is available in beta. 

https://github.com/cdk8s-team/cdk8s/tree/master/examples/go/hello

**Comment by iliapolo** [comment]
Announced here: https://aws.amazon.com/blogs/containers/announcing-the-general-availability-of-cdk8s-and-support-for-go/
