### ISSUE TITLE
(cdk8s+): TLS support for IngressV1Beta1

### ISSUE THREAD

**Issue by TheEdgeOfRage** [cdk8s-team/cdk8s#568]
### Description of the feature or enhancement:
Currently if you want to create an Ingress with TLS termination, you have to use the Ingress construct from cdk8s.

### Use Case:
Being able to avoid low-level constructs.

### Proposed Solution:

Either pass a `tls` prop to the `IngressV1Beta1` Construct or invoke the `addTls` method after instantiating the Ingress.

### Other:

PR: #569

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by TheEdgeOfRage** [comment]
Moved here: https://github.com/cdk8s-team/cdk8s-plus-17/issues/15

PR: https://github.com/cdk8s-team/cdk8s-plus-17/pull/14

**Comment by jabz-eks** [comment]
Hello,

How do you create ingress resources using CDK8s. could anyone share the examples for the same?
Thanks

**Comment by iliapolo** [comment]
@jabz-eks https://cdk8s.io/docs/latest/plus/ingress.html
