### ISSUE TITLE
ConfigMap data multiline and line length greater than 80 cause all \n to be removed.

### ISSUE THREAD

**Issue by p-gag** [cdk8s-team/cdk8s#588]
### Description of the bug:
When using Include primitive (or adding multi-line data) with a line that would render to more than 80 characters in the yaml, the output will change from  "some_data: |" to "some_data: >"

### Reproduction Steps:

Include the yaml
```
new Include(this, "a-name", {
  url: "bug.yaml",
});
```

bug.yaml
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-name
  namespace: my-namespace
data:
  a_buggy_section.conf: |
    [OUTPUT]
        Name            xyz
        Host            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  a_good_section.conf: |
    [OUTPUT]
        Name            abc
        Host            aaaaa
```

### Error Log:
Here is the output a_buggy_section.conf now have the '>'

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-name
  namespace: my-namespace
data:
  a_buggy_section.conf: >
    [OUTPUT]
        Name            xyz
        Host            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  a_good_section.conf: |
    [OUTPUT]
        Name            abc
        Host            aaaaa
```

### Environment:

  - 1.0.0-beta.11
  - macOS Big Sur, version 11.3.1

This is :bug: Bug Report

**Comment by felipesere** [comment]
Sorry to re-open this, but I still experience this issue.

In my case, I am generating annotations for vault and the value for template quickly exceeds the 80 chars-per-line limit and causes stray linebreaks.

In our case, the first line of the template is
```
{{- with secret "11111111111-222222222/monitoring/secret/3333-444444/3333-44444" -}}
```
Which is 83 characters long.
(I have replaced some values with equally-long repetitions of charts)

The actual string produced looks like this:
```
{{- with secret 
"11111111111-222222222/monitoring/secret/3333-444444/3333-44444" -}}
```
The remaining lines in that template all remain below 80 chars, so they stay intact.
