### ISSUE TITLE
Golang Examples

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s#637]
Add a few golang examples

**Comment by Hunter-Thompson** [comment]
@Chriscbr, can we also have a small example of how a test would look like for Go?

To convert the following in Go.

```TS
  const app = Testing.app();
  const chart = new Chart(app, 'test');

  new Deployment(chart, 'test', {

  });


  expect(Testing.synth(chart)).toMatchSnapshot();

```

**Comment by Chriscbr** [comment]
@Hunter-Thompson I've created an issue for it 👍  #652
