### ISSUE TITLE
consider adding a language-native interface for executing cdk8s (and other languages as well)

### ISSUE THREAD

**Issue by trondhindenes** [cdk8s-team/cdk8s#640]
### Description of the feature or enhancement:
I think it's fair to say that most use cases for cdk8s will include some kind of "wrapper" or entrypoint that handles the deploy process - at least that's how we're envisioning it. As such, it would be good if there were language-native interfaces to execute the "manifest build", instead of having to start a shell command to execute cdk8s. If I could do `cdk8s.generate()` in my python code instead, it would be so much cleaner.

For now we workaround this using shell command calls from our python code that performs the deploy, but it feels dirty because:
python --> runs the deploy scripts --> calls shell --> calls cdk8s --> calls python

The code called by cdk8s imports some of the same modules as our "wrapper" deploy scripts, but in a completely different process. It feels a bit wonky.

### Use Case:
See description above

### Other:
While I haven't looked into the testing functionality of cdk8s, there may already be stuff in there that works similarly do what I propose, since it's possible to test a manifest by generating it and then asserting its properties etc.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Chriscbr** [comment]
Under the hood, `cdk8s synth` runs your cdk8s code based on the value of "app" in `cdk8s.yaml`. For python, this defaults to the running a `main.py` script with pipenv - so there isn't any heavy lifting done by the CLI. If your wrapper code is also in Python, could you restructure the code to just directly call the cdk8s APIs?

e.g. you might create a function like:

```python
def generate():
    app = App()
    MyChart(app, "my-chart")
    app.synth()
```

and in your Python deployment code, you could call `generate()` wherever is needed.

**Comment by Chriscbr** [comment]
@trondhindenes  I see. Currently with the cdk8s you can call `synth` programmatically, but the manifests are still saved to the output directory, since it might save the resources in multiple files if you define multiple charts. Can you try putting your resources in a single `Chart` and then directly calling its `toJson()` method? I think this might achieve what you are looking for.

**Comment by trondhindenes** [comment]
hi, thanks. Calling `toJson` on the chart instance works!
