### ISSUE TITLE
Add examples of testing for each language

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s#652]
Include examples in https://cdk8s.io/docs/latest/examples/ for each language of how to use the testing framework.

Suggested by @Hunter-Thompson:

> can we also have a small example of how a test would look like for Go?
> 
> To convert the following in Go.
> 
> ```ts
>   const app = Testing.app();
>   const chart = new Chart(app, 'test');
> 
>   new Deployment(chart, 'test', {
> 
>   });
> 
> 
>   expect(Testing.synth(chart)).toMatchSnapshot();
> ```

Related: https://github.com/cdk8s-team/cdk8s-core/issues/35

**Comment by Hunter-Thompson** [comment]
keep

**Comment by Hunter-Thompson** [comment]
@Chriscbr, is there a recommended way the cdk8s team advises to unit test with golang? 

If there isn't a recommended way, I can share an example of how I do basic snapshot testing with cdk8s golang.

**Comment by Chriscbr** [comment]
@Hunter-Thompson We do not currently have any guidance at the moment, no. If you wanted to provide some examples that would be great!

Perhaps we could add a "Testing with cdk8s for Go" section to https://github.com/cdk8s-team/cdk8s/blob/master/docs/concepts/testing.md ?
