### ISSUE TITLE
Upgrade workflow failing

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s#673]
Latest `upgrade` workflow is failing: https://github.com/cdk8s-team/cdk8s/runs/3539386096

Error message:

```
Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  master
  Working base is branch 'master'
  /usr/bin/git remote prune origin
  fatal: could not read Username for 'github.com': No such device or address
  Error: The process '/usr/bin/git' failed with exit code 128
```

Possible cause: `PROJEN_GITHUB_TOKEN` (used by `upgrade.yml` workflow) has been misconfigured?

**Comment by iliapolo** [comment]
Yeap - I actually deleted all secrets from this repository since we aren't publishing anymore from it, forgot about the upgrade workflow that needs a `PROJEN_GITHUB_TOKEN` 👍

**Comment by iliapolo** [comment]
Fixed https://github.com/cdk8s-team/cdk8s/actions/runs/1217119876
