### ISSUE TITLE
make objects mutable

### ISSUE THREAD

**Issue by trondhindenes-nomono** [cdk8s-team/cdk8s#676]
### Description of the feature or enhancement:
One thing that surprised me with cdk8s is the apparent immutability of objects. Describing in use case

### Use Case:
Let's say I'm creating two deployments based on the same docker image - typical Django api + worker. The api has a port and service connected to it, the worker does not. As far as the deployment object goes, the only difference might be different container `command` attributes and slightly different labels/matchlabels.

I would expect cdk8s to allow me to create a `api_deployment = k8s.KubeDeployment()` with all the config that's needed, and then call `worker_deployment = deepcopy(api_deployment)`, and then simply replace the parts that need to be different:
`worker_deployment.spec.template.containers[0].command = worker_command` but this is seemingly not possible.

I know I can use escape hatches, but as far as I understand those are for last-resort stuff and json-patching isn't exactly programmer-friendly.

I know I also can create a custom Construct class which takes care of all similarities and just parameterize the differences (like command) but it feels like there should be a more lightweight way of doing stuff.

### Proposed Solution:
Expose the full "object structure" of construct objects so that they can be mutated

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by Chriscbr** [comment]
Is it possible you could create a construct to represent your deployment? See https://cdk8s.io/docs/latest/getting-started/#abstraction-through-constructs

For example, your construct could provide a couple of fields for the commands/options that are different between the two deployments, and then you can call

```python
api_deployment = MyCustomDeployment(app, command='...')
worker_deployment = MyCustomDeployment(app, command='...')
```

**Comment by trondhindenes-nomono** [comment]
Yup, it's definetely an option (and kindof what we're doing today). However, mutating an existing structure would be far easier.
