### ISSUE TITLE
Can not successfully execute cdk command in macOs

### ISSUE THREAD

**Issue by toughnoah** [cdk8s-team/cdk8s#710]
### Description of the bug:

when I ran cdk8s init go-app in Mac OS, I got this stderr:
Initializing a project from the go-app template
Importing k8s v1.22.0...
Importing resources, this may take a few moments...
go: downloading github.com/cdk8s-team/cdk8s-core-go/cdk8s v1.0.0-beta.59
go: downloading github.com/aws/constructs-go/constructs/v3 v3.3.160
go: downloading github.com/aws/jsii-runtime-go v1.37.0
fork/exec /var/folders/5x/rm_7vdxd7c38t593n3fz6sy40000gn/T/go-build136398091/b001/exe/cookie: exec format error
Error: error during project initialization: Error: Command failed: go run .

### Reproduction Steps:

npm install -g cdk8s-cli
mkdir hello
cd hello
cdk8s init go-app
Initializing a project from the go-app template

### Error Log:

fork/exec /var/folders/5x/rm_7vdxd7c38t593n3fz6sy40000gn/T/go-build136398091/b001/exe/cookie: exec format error
Error: error during project initialization: Error: Command failed: go run .

### Environment:

  - **Framework Version**:
  - **OS**:
node:  v1.14
macOs Big Sur 11.6

### Other:

It was the same error when I tried cdk8s synth. Should I specify os platform when install cdk8s?

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
Could you please share what version of Go you are using?
