### ISSUE TITLE
Run integration tests on latest version of Go

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s#721]
Currently the integration tests (https://github.com/cdk8s-team/cdk8s/blob/master/.github/workflows/integ.yml) run with Go 1.16, however Go 1.17 has been out for a few months now. We should probably test using the latest version of Go, or consider using a test matrix to test on the latest 2-3 major Go versions.

**Comment by iliapolo** [comment]
Giving this another shot to get prioritized
