### ISSUE TITLE
Support vm's

### ISSUE THREAD

**Issue by unicomp21** [cdk8s-team/cdk8s#729]
VirtualMachineInstanceReplicaSet, I don't see any support for it.

https://kubevirt.io/2020/KubeVirt-VM-Image-Usage-Patterns.html

**Comment by Hunter-Thompson** [comment]
You are welcome to extend APIObject and write your own.

See example :

https://github.com/opencdk8s/cdk8s-aws-lb-controller-api-object

**Comment by iliapolo** [comment]
@unicomp21 `VirtualMachineInstanceReplicaSet` is not a core kubernetes resource as I understand, right? In that as @Hunter-Thompson mentioned, it belongs in a separate third-party library.

If you'd like to request coverage for core kubernetes resources, please submit an issue [here](https://github.com/cdk8s-team/cdk8s-plus/issues/new)

**Comment by unicomp21** [comment]
Ok
