### ISSUE TITLE
Support compatibility with AWS CDK v2 / upgrade to constructs v10

### ISSUE THREAD

**Issue by kevindotglasson** [cdk8s-team/cdk8s#773]
[More info](https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html)

I was considering migrating to AWS CDK v2, however it looks like when attempting to install cdk8s in the same virtualenv that it can't solve an appropriate version of cdk8s.

```
# requirements.txt

aws-cdk-lib>=2.0.0rc1
constructs>=10.0.0
cdk8s
```

**Comment by Chriscbr** [comment]
Reopened since the initial PR https://github.com/cdk8s-team/cdk8s-core/pull/150 did not work as intended for Go users, and had to be reverted.

**Comment by msessa** [comment]
@Chriscbr is the new approach to just branch off and maintain v1/v2 main lines?

**Comment by Chriscbr** [comment]
@msessa I think so, yes, though it's not set in stone. We are also still considering how long to maintain the v1 branch. But either way we aim to make upgrading to v2 straightforward. 🙂

**Comment by Chriscbr** [comment]
cdk8s v2 has been published with support for constructs v10 - but I'm going to keep this issue open to track the remaining tasks:

- [ ] Update / add cdk8s v2 starter code in all supported languages
- [ ] Add support for cdk8s v2 in cdk8s-plus libraries
- [ ] Update documentation on the website to explain the difference between cdk8s v1 and cdk8s v2

**Comment by BwL1289** [comment]
@Chriscbr thanks so much for this! Not sure this is the right thread for this (please let me know if it is not! I'm happy to create a new one [here](https://github.com/cdk8s-team/cdk8s-plus) instead) but is there any plan to make cdk8s-plus-XX compatible with AWS CDK v2 as well?

Currently, looks like cdk8s-plus-22-1.0.0b157 depends on `constructs<4.0.0 and >=3.3.249`

```
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 3), -r requirements.txt (line 4), cdk8s, cdk8s-plus-22==1.0.0b157 and constructs because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested constructs
    aws-cdk-lib 2.17.0 depends on constructs<11.0.0 and >=10.0.0
    cdk8s 2.2.48 depends on constructs<11.0.0 and >=10.0.0
    cdk8s-plus-22 1.0.0b157 depends on constructs<4.0.0 and >=3.3.249
```

Thanks again!

**Comment by Chriscbr** [comment]
Hi @BwL1289, thanks for calling this out! Yep, we're also planning to make cdk8s+ compatible with AWS CDK v2 as well. I've updated my earlier comment to add it to the list. Stay tuned 👍

**Comment by jordangullen** [comment]
Hi @Chriscbr, I'm also keen to see support of cdk8s+ with AWS CDK v2.

Do you have a rough date for release and should we follow this thread for updates?

Thanks for all the awesome work!

**Comment by iliapolo** [comment]
This should now be resolved. Latest version of cdk8s+ only support constructs 10, and for the cdk8s core library, use cdk8s v1 for working with constructs v3 (e.g v1 of AWS CDK), and use cdk8s v2 for working with constructs v10 (e.g AWS CDK v2)
