### ISSUE TITLE
State Management and Diffs?

### ISSUE THREAD

**Issue by jonathanbbai** [cdk8s-team/cdk8s#848]
### Description of the feature or enhancement:

The largest thing holding this back from replacing Helm/TF/etc completely is the lack of state management and diffs.

Unless I'm missing something, when you get rid of a construct from your code and re synth, it doesn't actually provide a way to delete the missing construct. 

If multiple people are working on a cdk8s codebase, how are they suppose to avoid tripping over editing people's configurations.
And how would you know that when you're editting the code, it isn't synthing a missing yaml that was there before and now the old yaml is still applied to the K8s cluster and no one would notice.

### Other:

Are there ways to get around this and add some state management to cdk8s?

---

This is a :rocket: Feature Request

**Comment by shinebayar-g** [comment]
Looks like commiting yaml files into the git repository is all we have atm :|
