### ISSUE TITLE
Helm support to take account of Capabilities.APIVersions

### ISSUE THREAD

**Issue by dniasoff** [cdk8s-team/cdk8s#862]
### Description of the feature or enhancement:
As I am sure you must be aware by now, Kubernetes has many, many, many versions. Each version supports different APIs and each new version deprecates APIs that were considered "beta" in the past.

For instance ```extensions/v1beta1``` for Ingress was deprecated in  v1.14+ and unavailable since v1.22+.

When you deploy a helm chart, helm can take into account the specific clusters API capabilities and adapts the manifests accordingly (if implemented in code).

However, helm support in CDK8s is currently a "one size fits all" with no option of selecting what APIs to use meaning that the cdk8s output might not work on the cluster you are deploying to.

### Use Case:

I am trying to render a helm chart for [kong](https://docs.konghq.com/gateway/2.7.x/install-and-run/helm/) and the manifest cannot be deployed to a version 1.22 Kubernetes cluster

### Proposed Solution:
I can see 3 possible ways of addressing this

1. Adding a parameter to the Helm method allowing for selection of major Kubernetes version
2. Adding helm support to the version-specific implementations such as cdk8s-plus-22
3. Adding a parameter to manually override API versions such as ```--api-versions=networking.k8s.io/v1``` 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by dniasoff** [comment]
Been doing some more research on this and it appears to be a major limitation of the helm template command. 

Helm template will only honour ```--api-versions=networking.k8s.io/v1``` if ```--validate``` is also passed. However, this needs a connection to a cluster and will fail if there are conflicting resources on the cluster breaking your build process.

There really needs to be a way to tell Helm template some information about your cluster's capabilities without having to resort to connecting and validating using a real cluster as build servers typically don't have access to Kubernetes clusters.

As cdk8s relies on the helm template command, there doesn't appear to be a workaround unless I am missing something.

**Comment by dcharbonnier** [comment]
Can we reopen this issue? This is a priority/p1 issue and I think it's still relevant.

**Comment by erikschul** [comment]
@dcharbonnier It works for me with the flag. Does it not work for you?

```
helmFlags: ["--api-versions", "monitoring.coreos.com/v1"]
```

For me, ArgoCD helm chart requires it for generating ServiceMonitors.
```
{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.repoServer.metrics.enabled .Values.repoServer.metrics.serviceMonitor.enabled }}
```
