### ISSUE TITLE
Add SECURITY.md to repo

### ISSUE THREAD

**Issue by jeefy** [cdk8s-team/cdk8s#875]
The CNCF is starting to use a [new tool](https://clomonitor.io/projects/cdk8s/cdk8s) to track project requirements and best practices.

One pretty easy fix to increase cdk8s' score would be to add either a SECURITY.md file OR add a `Security` header in the main README file. 

Here are some examples of what we're looking for:

- https://github.com/antrea-io/antrea/blob/main/SECURITY.md
- https://github.com/kubernetes/community/blob/master/SECURITY.md
- https://github.com/prometheus/prometheus/blob/main/SECURITY.md

Feel free to ping me with any questions. Thank you!

**Comment by iliapolo** [comment]
@jeefy I see some project using a specific `CNCF` email address dedicated to the project. Does cdk8s also have a `cncf-cdk8s-maintainers` address we could leverage?

**Comment by jeefy** [comment]
Yup! https://lists.cncf.io/g/cncf-cdk8s-maintainers exists for you to use. 

That said, do you want Security issues going to that email? Or do you think this warrants a separate email (like `cncf-cdk8s-security`)?

**Comment by iliapolo** [comment]
@jeefy `cncf-cdk8s-security` would be nice :)

**Comment by jeefy** [comment]
Can someone from the project create a [Service Desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) ticket and include the emails of the initial members? CC/Assign me on the initial request and I can knock it out pretty quick.

Thanks!

**Comment by iliapolo** [comment]
@jeefy I created a ServiceDesk request: https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1591?created=true

Sorry for the (very) long delay...

**Comment by iliapolo** [comment]
Done
