### ISSUE TITLE
Document aliased imports

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s#883]
When importing two CRD's that share the same group id, one needs to use aliased imports, otherwise the imports will override one another.

> See https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests/setup for an example of CRD's that share group id.

That is, instead of having:

```yaml
imports:
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/setup/0alertmanagerCustomResourceDefinition.yaml
```

We need to alias the imports like so:

```yaml
imports:
  - alertmanagerconfig:=https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml
  - alertmanager:=https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/setup/0alertmanagerCustomResourceDefinition.yaml
```

This functionality is not documented. We should add to our CRD's [section](https://cdk8s.io/docs/latest/cli/import/#crds).

#### Side Note

It would be nice if the CLI could warn before overriding an import and suggest an alias import with a link to the new documentation section.

**Comment by mcouthon** [comment]
Would it be possible to identify that both are coming from the same namespace, merge the two into a single eg Python file, and allow importing both from it?

**Comment by iliapolo** [comment]
> @iliapolo do you think is this what happening there -> #881

I don't think it's related actually. I need to a closer look into what's happening there.

**Comment by iliapolo** [comment]
@mcouthon 

> Would it be possible to identify that both are coming from the same namespace, merge the two into a single eg Python file, and allow importing both from it?

Should be doable I think. Can you create a feature request?

**Comment by mcouthon** [comment]
Sure: #885 🙇
