### ISSUE TITLE
Supporting Runtime Contexts

### ISSUE THREAD

**Issue by pmkuny** [cdk8s-team/cdk8s#886]
### Description of the feature or enhancement:

Currently, the CDK v2 supports [Runtime Contexts](https://docs.aws.amazon.com/cdk/v2/guide/context.html). This context allows for various values to be written to a file (default `context.json`), read from that file, and retrieved during runtime deployment. Additionally, these context values can be determined from things such as environment variables and arguments passed during deployments.

While a file input/output method is certainly possible in all the languages CDK8s currently supports, having a more structured form of functionality that is able to inject/try values, as well as modify a variety of variables based on the running environment would be handy.

Specifically, in writing CDK8s code, it would be handy to have the ability to execute something similar to CDK's `construct.node.tryGetContext` to inject runtime variables into our codebase. 

**I understand that this may include a feature scope that CDK8s wasn't even intended for - the CDK context is used to set environmental settings (such as AWS Account) that may not even applicable to Kubernetes cluster management or creation.** 

### Use Case:

A built-in method of retrieving dynamic values at runtime so sensitive information doesn't have to be hardcoded into the codebase is my specific use case, but I think this could extend to other uses cases where cluster environment was interpolated from the context (similar to how CDKv2 currently operates). I could see this benefiting those who intend to use CDK8s to manage multiple K8s clusters.

### Other:

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by valentinsavenko** [comment]
I also had to build this functionality on my own with Environment Variables and passing down of params. 
[Runtime Contexts](https://docs.aws.amazon.com/cdk/v2/guide/context.html) close to cdk would enable us to have 2 repos with very similar setups, as we also use cdk internally and already like and use this.

**Comment by jwenz723** [comment]
Since a cdk8s app is written using a coding language you could add code to ingest environment variables or a config file and then pass the received input into the cdk8s constructs.
