### ISSUE TITLE
Question: about cdk8s use case

### ISSUE THREAD

**Issue by ulutinquity** [cdk8s-team/cdk8s#953]
Can cdk8s be used inside bigger application code base to synth YAML (using `app.synthYaml()`) to manually pass YAML to kubectl.
Basically I want to synth YAML during runtime on request, not pre-synth it.
Is this a valid use case or is it not supposed to be used like that?

**Comment by cedricmckinnie** [comment]
I'm also interested in this. Thanks!

**Comment by iliapolo** [comment]
@ulutinquity appologies for the (very) delayed response. This is a perfectly valid and supported use case. If you're having any issues with it let us know 👍
