### ISSUE TITLE
K8S CronJob spec.jobTemplate.spec.template.spec.restartPolicy MUST be set

### ISSUE THREAD

**Issue by NPellet** [cdk8s-team/cdk8s#958]
### Description of the bug:
I'm still discovering cdk8s and that I managed to generate invalid manifests without warnings surprised me.
Actually it's more than that just the missing restartPolicy, I find that there are many ways to create invalid manifests:

```javascript
    const cronjob2 = new KubeCronJob(this, "test");
```

This is valid ts code but outputs

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: client-test-c8ff0b99
```

which is not a valid manifest.
I would expect that in that case the manifest wouldn't be created, maybe with a warning (I guess it points out to the larger issue to figure whether or not output manifests should be linted or not)

But still, assuming it's correct to allow users not to provide an argument, I feel like in case they do decide to provide one, at least the spec should be provided, while the type is:

```typescript
export interface KubeCronJobProps {
    readonly metadata?: ObjectMeta;
    readonly spec?: CronJobSpec;
}
```

And pointing to my more specific issue, in the case of a CronJobSpec, the restartPolicy must be set and I expected TS to enforce this. IMHO using a strong system typing system that can provide invalid manifests sort of defeats the purpose of the whole typing system ?
 
### Reproduction Steps:

```javascript
    const cronjob2 = new KubeCronJob(this, "test");
```

or 

```javascript

    const cronjob2 = new KubeCronJob(this, "test", {
      metadata: {
        name: "somename",
        namespace: "namespace",
      },
      spec: {
        schedule: "* * * * *",
        jobTemplate: {
          spec: {
            template: {
              spec: {
                containers: [
                  {
                    name: "main",
                    image: "img",
                  },
                ],
              },
            },
          },
        },
      },
    });
```

### Error Log:
The CronJob "***" is invalid: spec.jobTemplate.spec.template.spec.restartPolicy: Required value: valid values: "OnFailure", "Never"

### Environment:

```json
"dependencies": {
    "cdk8s": "^2.3.79",
    "cdk8s-plus-22": "^2.0.0-rc.77",
    "constructs": "^10.1.71"
  },
```

Seeing that the optional typing seems very prevalent across the k8s constructs, I assume this is by design.
So I guess that validating the manifests is up to the user ? If so, a quick mention in the docs might be warranted ?

---

This is :bug: Bug Report

**Comment by vinayak-kukreja** [comment]
Hey @NPellet thank you for letting us know about this. 

The constructs that have `Kube` prefix are auto generated by us(L1 or Level 1 constructs i.e. [cdk8s](https://cdk8s.io/docs/latest/)) from Kubernetes specification. Looks like restart policy has [default value](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) within Kubernetes. These L1s do not have any custom logic from us and mimics what Kubernetes specification is.

We do offer L2s or Level 2 constructs i.e. [cdk8s+](https://cdk8s.io/docs/latest/plus/) for [CronJob](https://cdk8s.io/docs/latest/plus/cdk8s-plus-24/cronjob/) resource. Is there a reason that you are not using this? 
L2s provide better abstraction and will ease your development effort. For instance, if you do not provide a `restartPolicy` in the L2 API, we would add a [default](https://github.com/cdk8s-team/cdk8s-plus/blob/k8s-26/main/src/job.ts#L74) which would not fail the manifest deployment.
