### ISSUE TITLE
What's New Post

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s#977]
For the GA and the validation mechanism.

**Comment by iliapolo** [comment]
Created ticket: https://issues.amazon.com/issues/D57342224

**Comment by devkapilbansal** [comment]
> Created ticket: https://issues.amazon.com/issues/D57342224

Is this issue related to Amazon?

**Comment by iliapolo** [comment]
Content ready. Need to send for approval.

**Comment by iliapolo** [comment]
Sent for approval. Awaiting response.

**Comment by iliapolo** [comment]
All approved. Waiting on staging.
